---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# immunoeasy

<!-- badges: start -->
<!-- badges: end -->

The goal of immunoeasy is to make immunologist life easier with clear functions. 

## Installation

You can install the released version of immunoeasy from [Github](https://github.com/itamuria/immunoeasy) with:

``` r

# library(devtools)
# devtools::install_github("itamuria/immunoeasy")
library(remotes)
remotes::install_github("itamuria/immunoeasy")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(immunoeasy)
## basic example code
```

### Load package and data

The data can be loaded from github or can be found in the package dataset. 

```{r}
rm(list = ls())
time_doc1 <- Sys.time()
library(immunoeasy)
if (!require("pacman")) install.packages("pacman")
library(pacman)
pacman::p_load(ggplot2, repmis,RColorBrewer,SuperLearner, gam,splines,foreach,glmnet,Matrix,nnet,polspline,e1071,xgboost)
# Download data
source_data("https://github.com/itamuria/expose_dataset/blob/master/20180818_dtaset.RData?raw=true")
set.seed(22222)
```

